### ISSUE TITLE
ERM Single

### ISSUE THREAD

**Issue by herman85** [frenyaif/rm-single-release#1]
**Latar belakang permintaan (permasalahan)**
...
Ketika pasien ingin di rujuk ke fasilitas kesehatan lanjutan / pemeriksaan penunjang ter dokumentasi
**Solusi**
...
Ada cacatan dokter / keterangan
**Alternatif solusi**
...

**Catatan tambahan**
...

**Comment by frenyaif** [comment]
> @herman85 
> **Latar belakang permintaan (permasalahan)**
> Ketika pasien ingin di rujuk ke fasilitas kesehatan lanjutan / pemeriksaan penunjang ter dokumentasi
>
> **Solusi**
> Ada cacatan dokter / keterangan

Terima kasih masukannya mas.

Catatan dokter memungkinkan untuk ditambahkan sesaat sebelum kunjungan diselesaikan. Tapi saya mau memastikan satu hal. Jika latar belakangnya adalah pasien dirujuk dan membutuhkan catatan dokter, apakah dibutuhkan cetakan rujukan dari rm-single?

**Comment by herman85** [comment]
> > @herman85
> > **Latar belakang permintaan (permasalahan)**
> > Ketika pasien ingin di rujuk ke fasilitas kesehatan lanjutan / pemeriksaan penunjang ter dokumentasi
> > **Solusi**
> > Ada cacatan dokter / keterangan
> 
> Terima kasih masukannya mas.
> 
> Catatan dokter memungkinkan untuk ditambahkan sesaat sebelum kunjungan diselesaikan. Tapi saya mau memastikan satu hal. Jika latar belakangnya adalah pasien dirujuk dan membutuhkan catatan dokter, apakah dibutuhkan cetakan rujukan dari rm-single?

**Comment by herman85** [comment]
> > @herman85
> > **Latar belakang permintaan (permasalahan)**
> > Ketika pasien ingin di rujuk ke fasilitas kesehatan lanjutan / pemeriksaan penunjang ter dokumentasi
> > **Solusi**
> > Ada cacatan dokter / keterangan
> 
> Terima kasih masukannya mas.
> 
> Catatan dokter memungkinkan untuk ditambahkan sesaat sebelum kunjungan diselesaikan. Tapi saya mau memastikan satu hal. Jika latar belakangnya adalah pasien dirujuk dan membutuhkan catatan dokter, apakah dibutuhkan cetakan rujukan dari rm-single?

jika melihat dari tampilan pada rm-single yg terdiri dari anamnesis, terapi, dx dll itu menjadi suatu resume medis ya bunyi cetakannya mas ? di butuhkan ato tidak belum tau saat ini, semoga user yang nanti nya menggunakan bisa memberikan masukan mas.

**Comment by frenyaif** [comment]
Sependek yang saya tahu, catatan dokter tersebut dapat berbunyi apa saja yang melatar belakangi seorang pasien dirujuk. Apakah ada catatan menyangkut kondisi medis pasien? Sangat mungkin ada. Dan saya rasa dokter perujuk paham betul apa yang dibutuhkan di dalam catatan tersebut, sehingga konsep catatannya lebih fleksibel jika dibebaskan.

Oke siap, sesegera mungkin saya tambahkan.
